services:
  - type: web
    name: ngo-cms-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py create_admin   # or createsuperuser --noinput if no custom command
    startCommand: gunicorn ngo_cms.wsgi:application
    envVars:
      - key: DB_NAME
        value: ngo_db_hfxj
      - key: DB_USER
        value: ngo_db_hfxj_user
      - key: DB_PASSWORD
        value: q53HqXMEwla70tPiSLMCNj0Ospp5jTWO
      - key: DB_HOST
        value: dpg-d57vve9r0fns73dlodcg-a.virginia-postgres.render.com  # ✅ external hostname
      - key: DB_PORT
        value: 5432
      - key: SECRET_KEY
        value: django-insecure-x0nqmv+(&bp^jt_jf*y@jqny6jla=t25_pw@2a_gio5w$(ry6=
      - key: DEBUG
        value: False
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin@123
