# Generated by Django 5.0.2 on 2025-12-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mission & Vision', max_length=100)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='site_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
