# Generated by Django 5.0.2 on 2025-12-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='core_values',
            field=models.TextField(blank=True, help_text='Enter core values separated by semicolons (;)', null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='programs',
            field=models.TextField(blank=True, help_text='Enter programs separated by semicolons (;)', null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='story_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(default='About Us', max_length=100),
        ),
    ]
